export const POSTS_RECEIVED = "POSTS_RECEIVED";
export const POST_SELECT = "POST_SELECT";
export const PREVIOUS_POST = "PREVIOUS_POST";
export const NEXT_POST = "NEXT_POST";
export const PRELOAD_INIT = "PRELOAD_INIT";
export const PRELOAD_COMPLETE = "PRELOAD_COMPLETE";
export const PRELOAD_RESET = "PRELOAD_RESET";
export const TOGGLE_ASPECT_RATIO = "TOGGLE_ASPECT_RATIO";
export const TOGGLE_AUTO_PLAY = "TOGGLE_AUTO_PLAY";

export const PRELOAD_STATES = {
  UNINITIALIZED: "UNINITIALIZED",
  LOADING: "LOADING",
  COMPLETE: "COMPLETE"
};
